name : Publish Python distributions to PyPI

on :
  push:
    tags:
      - "*"


jobs:
  bulid-publish:
    name: Build and publish Python  distributions to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --wheel --outdir dist/

      - name: Publish distribution to PyPI
        if: startWith(github.ref,'refs/tags')
        uses: pype/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}